### ISSUE TITLE
release v1.0.0

### ISSUE THREAD

**Issue by topliceanu** [topliceanu/mongoose-gen#7]
## todos
- [ ] port the codebase to coffeescript for better maintenenace
- [x] new api: extend `mongoose.Schema` class to support schema generation from simple json documents.
- [ ] support jsonschema (3) with extensions
- [x] support all mongoose features.

## packages solving the same or similar problems
1. https://github.com/work-in-progress/mongoose-from-json-schema
2. https://github.com/adityab/json-mongoose-schemadef
3. https://github.com/Clever/json-schema-converter (best by far!)
 - simply constructs an object which can be easily passed to the `mongoose.Schema` constructor
